error: No such command 'init-db' when I run this, even though the line exists in db.py
